todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

todo/todoapp/urls.py
from django.urls import path
from . import views

app_name = 'todoapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update'),
    path('home/', views.TaskListView.as_view(), name='home'),
    path('details/<int:pk>/', views.TaskDetailView.as_view(), name='details'),
    path('edit/<int:pk>/', views.TaskUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.TaskDeleteView.as_view() ,name='delete'),

]

todo/todoapp/models.py
from django.db import models

class Task(models.Model):
    name = models.CharField(max_length=100)
    priority = models.CharField(max_length=50)
    date = models.DateField(auto_now=False, auto_now_add=False)
    
    
    def __str__(self):
        return self.name
    

todo/todoapp/forms.py
from . models import Task
from django import forms

class TodoForm(forms.ModelForm):
    
    class Meta:
        model = Task
        fields = ("name", "priority")

todo/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from  django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView

from .models import Task
from .forms import TodoForm

class TaskListView(ListView):
    model = Task
    template_name = "index.html"
    context_object_name = 'task'

class TaskDetailView(DetailView):
    model = Task
    template_name = "details.html"
    context_object_name = 'task'
    
class TaskUpdateView(UpdateView):
    model = Task
    template_name = "edit.html"
    context_object_name = 'task'
    fields = ('name', 'priority')

    def get_success_url(self):
        return reverse_lazy('details', kwargs={'pk':self.object.id})

class TaskDeleteView(DeleteView):
    model = Task
    template_name = "delete.html"
    success_url = reverse_lazy('home')



def index(request):
    details = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('name', '')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date', '')
        task = Task(name=name, priority=priority, date=date)
        task.save()
    return render(request, 'index.html', {'task': details})


def delete(request, id):
    if request.method == 'POST':
        task = Task.objects.get(id=id)
        task.delete()
        return redirect('/')
    return render(request, 'delete.html')


def update(request, id):
    task = Task.objects.get(id=id)
    form = TodoForm(request.POST or None, instance=task)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'update.html', {'form':form, 'task':task} )

todo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
    <title>TODO</title>
</head>
<body>
    <div class="container-fluid">
        <div class="col-md-12">
            <div class="banner">
                <h1>ToDo</h1>
            </div>
        </div>
    </div>
    {% block body %}
    {% endblock body %}
</body>
</html>

todo/templates/delete.html
{% extends 'base.html' %}
<title>Delete</title>
{% block body %}
<form action="" method="post">
    {% csrf_token %}
    <h2>Task completed Successfully ? ?</h2> <br> 
    <div class="submit">
        <input type="submit" value="Yes" class="btn btn-danger">
    </div>
    
    
</form>

{% endblock body  %}

todo/templates/details.html
{% extends 'base.html' %}
{% block body %}

    <h4>-Tasks to be Completed-</h4>
 
    <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-text">Priority: {{task.priority}}</h5>
          <h5 class="card-title">Task: {{task.name}}</h5>
          <h5 class="card-text">Planned on: {{task.date}}</h5>
          <a href="{% url 'todoapp:delete' task.id %}" class="btn btn-danger">Done</a>
          <a href="{% url 'todoapp:update' task.id %}" class="btn btn-success">Update</a>
        </div>
      </div>
      <br>
</div> 

{% endblock body %}

todo/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="post">
    {% csrf_token %}
        {{form.as_p}}
    <div class="submit">
        <input type="submit" value="Update" class="btn btn-success">
    </div>
    
    
</form>

{% endblock body  %}

todo/templates/index.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form action="" method="post">
                {% csrf_token %}
                
                <label for="name" class="form-label">Task Name</label>
                <input type="text" class="form-control" name='name' placeholder="Task Name"> <br> <br>
                <label for="priority" class="form-label"> Priority</label>
                <input type="text" class="form-control" name="priority" placeholder="Priority Level 'Low'"> <br> <br>
                <input type="date" class="form-control" name="date" placeholder="" Level"> <br> <br>
                <input type="submit" class="btn btn-success">
    
            </form>
        </div>
        <div class="col-md-6">
            <h4>-Tasks to be Completed-</h4>
            {% for i in task %}
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-text">Priority: {{i.priority}}</h5>
                  <h5 class="card-title">Task: {{i.name}}</h5>
                  <h5 class="card-text">Planned on: {{i.date}}</h5>
                  <h5 class="card-text">id: {{i.id}}</h5>
                  <a href="{% url 'todoapp:delete' i.id %}" class="btn btn-danger">Done</a>
                  <a href="{% url 'todoapp:update' i.id %}" class="btn btn-success">Update</a>
                </div>
              </div>
              <br>
            {% endfor %}
        </div>  
    </div>
</div>

       
    
{% endblock body %}
    



 

todo/templates/update.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="post">
    {% csrf_token %}
        {{form.as_p}}
    <div class="submit">
        <input type="submit" value="Update" class="btn btn-success">
    </div>
    
    
</form>

{% endblock body  %}